apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "karpenter.fullname" . }}-nodeclaims-cleanup
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "karpenter.sh"
  resources:
  - nodeclaims
  verbs:
  - list
  - get
