apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "karpenter.fullname" . }}-nodeclaims-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
spec:
  podSelector:
    matchLabels:
      {{- include "karpenter.labels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
