kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "karpenter.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.karpenter.controller.metrics.port }}
          protocol: TCP
        - port: {{ .Values.karpenter.controller.healthProbe.port }}
          protocol: TCP
        - port: {{ .Values.karpenter.webhook.port }}
          protocol: TCP
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
